apiVersion: v1
kind: Service
metadata:
  name: visitor-service
spec:
  selector:
    app: visitor-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer   # Exposes app publicly on EC2