# visitor-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: visitor-service
spec:
  selector:
    app: visitor-app
  ports:
    - protocol: TCP
      port: 5000         # ClusterIP port
      targetPort: 5000   # Container port
      nodePort: 31816    # NodePort (30000-32767)
  type: NodePort